include: package:pedantic/analysis_options.yaml

linter:
  rules:
    avoid_shadowing_type_parameters: false
    omit_local_variable_types: false
    prefer_collection_literals: false
    unnecessary_this: false
    prefer_generic_function_type_aliases: true
    always_use_package_imports: true
    avoid_types_as_parameter_names: true
    always_declare_return_types: true
    avoid_types_on_closure_parameters: true


analyzer:
  enable-experiment:
    - non-nullable